apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: bored
build:
  artifacts:
  - image: bored
    sync:
      infer:
        - ".dockerignore"
        - "src/**/*"
        - "*.ts"
        - "*.js*"
        - "yarn.*"
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
    - kubernetes/deployment.yaml
    - kubernetes/service.yaml
